server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/conding?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    #Hikari连接池配置
    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      #空闲连接存活最大时间 默认
      idle-timeout: 180000
      #连接池最大连接数，默认是10
      maximum-pool-size: 10
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      #连接池母子
      pool-name: MyHikariCP
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #Elasticsearch配置
  elasticsearch:
    jest:
      uris: http://127.0.0.1:9200
  #Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: pwd
    #连接池
    lettuce:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 200
        min-idle: 200
    timeout: 100
  cache: redis
